image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
<<<<<<< HEAD
    - ma  # ветка git
=======
    - main  # ветка git
>>>>>>> 4686861a0d2591f636c9676548ba8f5f766093ec

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
  - chmod +x gradlew

build_script:
  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации
